services:
  web:
    build: ./
    command: gunicorn base.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    expose:
      - 8000

  nginx:
    build: ./nginx
    ports:
      - 8123:80
    depends_on:
      - web