services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn base.wsgi:application --bind 0.0.0.0:8000
#    volumes:
#      - static_volume:/home/worker_user/app/web/static
    expose:
      - 8000

  nginx:
    build: ./nginx
#    volumes:
#      - static_volume:/home/worker_user/app/web/static
    ports:
      - 8123:80
    depends_on:
      - web

#volumes:
#  static_volume: