# Generated by Django 5.1.6 on 2025-03-04 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_bin', '0003_remove_order_total_cost_order_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount in percents.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_bin.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax in percents.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_bin.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
            },
        ),
    ]
