# Generated by Django 5.1.6 on 2025-03-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_bin', '0004_discount_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'US Dollar'), ('eur', 'Euro')], default='usd', max_length=3, verbose_name='Currency'),
        ),
    ]
